### ISSUE TITLE
gene.list

### ISSUE THREAD

**Issue by TeaByrd** [UoS-HGIG/GenePy#2]
Hey guys, 
I'm facing the problem, that I don't know how the "gene.list" should be formatted. 

In the last step: 

while read gene:
do
sh GenePy_1.2.sh $gene ;
done< gene.list

my current gene.list is a text file with comma separated gene names:
MFN2,SELENOW,TOR1A,RTN4R, etc... .

When I apply this, nothing really happens. The output folders remain empty. 
Can you help me?

Best regards,
Thomas

**Comment by rjohnp** [comment]
Hi Thomas,

the gene.list needs to be one line per gene to work with the `read` command.

Reuben

**Comment by TeaByrd** [comment]
Thx Reuben
